# Ref:
Book: Qingkai Kong, Timmy Siauw, Alexandre Bayen - Python Programming and Numerical Methods_ A Guide for Engineers and Scientist-Academic Press (2020)\
CHAPTER 14 : LINEAR ALGEBRA AND SYSTEMS OF LINEAR EQUATIONS\
Page: 248

TRY IT! Use Gauss elimination to solve the following equations:\
4x_1 + 3x_2 − 5x_3 = 2,\
−2x_1 − 4x_2 + 5x_3 = 5,\
8x_1 + 8x_2 = −3.

In [1]:
from numpy import array, zeros

In [3]:
a = array([[4, 3, -5],
           [-2, -4, 5],
           [8, 8, 0]], float)
b = array([2, 5, -3], float)

In [4]:
n = len(b)
x = zeros(n, float)

In [5]:
# Elimination
for k in range (n-1):
  for i in range (k+1, n):
    if a[i,k] == 0: continue
    factor = a[k,k]/a[i,k]
    for j in range(k, n):
      a[i,j] = a[k,j] - a[i,j]*factor
    b[i] = b[k] - b[i]*factor

print(a)
print(b)

[[ 4.  3. -5.]
 [ 0. -5.  5.]
 [ 0.  0. 30.]]
[ 2.  12.  -5.5]


In [6]:
# Back-substitution
x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
  sum_ax = 0
  for j in range(i+1, n):
    sum_ax += a[i,j] * x[j]
  x[i] = (b[i] - sum_ax) / a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[ 2.20833333 -2.58333333 -0.18333333]
